
title: base device binding
version: 0.1

description: >
    Binding for device

properties:
    compatible:
        type: string-array
        category: required
        description: compatible strings
        generation: define

    reg:
        type: array
        description: register space
        generation: define
        category: optional

    reg-names:
        type: string-array
        description: name of each register space
        generation: define
        category: optional

    interrupts:
        type: array
        category: optional
        description: interrupts for device
        generation: define

    interrupt-names:
        type: string-array
        category: optional
        description: name of each interrupt
        generation: define

    label:
        type: string
        category: optional
        description: Human readable string describing the device (used by Zephyr for API name)
        generation: define
